import Navigation from '@/components/navigation/Navigation'
import './globals.css'
import type { Metadata } from 'next'
import { Quicksand } from 'next/font/google'

const quicksand = Quicksand({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.className} text-blue-900 flex font-semibold text-lg`}
      >
        <Navigation />
        {children}
      </body>
    </html>
  )
}
